# -*- coding: utf-8 -*-
"""DS7_Mongodb.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ot2KkbZ8oPsSlm722bZlNrcQ1Cl-Kn_T

MongoDB with PyMongo
LSDS Unit 3 Sprint 2 Module 3

Some resources:

https://docs.atlas.mongodb.com/getting-started/

https://api.mongodb.com/python/current/

HN Discussion on MongoDB versus PostgreSQL/SQLite: https://news.ycombinator.com/item?id=19158854

[ ]
"""

!curl https://ipecho.net/plain

"""KshiHOIepQnItbwa"""

!python --version

!pip install pymongo

import pymongo

client = pymongo.MongoClient("mongodb://admin:KshiHOIepQnItbwa@cluster0-shard-00-00-jhqja.mongodb.net:27017,cluster0-shard-00-01-jhqja.mongodb.net:27017,cluster0-shard-00-02-jhqja.mongodb.net:27017/test?ssl=true&replicaSet=Cluster0-shard-0&authSource=admin&retryWrites=true&w=majority")
db = client.test

db

#check how may machines 
client.nodes

help(db)

dir(db.test)

help(db.test.insert_one)

#insert a document
db.test.insert_one({'x':1})

db.test.count_documents({'x':1})

db.test.insert_one({'x':1})

# count how many functions there are aggain 
db.test.count_documents({'x':1})

db.test.find_one({'x':1
                  })

db.test.find({'x':1
                  })

curs = db.test.find({'x':1})

dir(curs)

list(curs)

anthony_doc = {
      'favorite_animal': ['leafy sea dragon', 'dragon']
      }

rudy_doc = {
    'favorite_animal' : 'Koala',
    'favorite_color' : 'Blue'
}

coop_doc = {
    'favorite_animal' : 'Pangolin'
}

db.test.insert_many([anthony_doc, rudy_doc, coop_doc])

list(db.test.find())

#now let's make more docs.

more_docs = []
for i in range(10):
    doc = {'even': i % 2 == 0}
    doc['value'] = i
    more_docs.append(doc)

more_docs

db.test.insert_many(more_docs)

list(db.test.find({'favorite_animal': 'Pangolin'}))

list(db.test.find({'even': False}))

db.test.update_one({'value' : 3},{'$inc':{'value': 5}})

list(db.test.find())

db.test.update_many({'even' : True},{'$inc':{'value': 100}})

list(db.test.find({'even' : True}))

db.test.delete_many({'even' : False})

list(db.test.find())

rpg_character = (1, "King Bob", 10, 3, 0, 0, 0)

# wrap in a dictionary so that we can insert it 

db.test.insert_one({'rpg_character': rpg_character})

db.test.insert_one({
    'sql_id': rpg_character[0],
    'name': rpg_character[1],
    'hp': rpg_character[2],
    'level': rpg_character[3]
})

list(db.test.find())

